export const GET_ERRORS = 'GET_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const SET_CSRF = 'SET_CSRF';
// CATEGORY
export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_TAG = 'GET_ALL_CATEGORY_TAG';
export const CREATE_NEW_CATEGORY = 'CREATE_NEW_CATEGORY';
export const GET_CATEGORY_WITH_PARAMS = 'GET_CATEGORY_WITH_PARAMS';
export const GET_CATEGORY_TYPE_WITH_PARAMS = 'GET_CATEGORY_TYPE_WITH_PARAMS';
export const GET_CATEGORY_BANNER_CATEGORY = 'GET_CATEGORY_BANNER_CATEGORY';
export const GET_CATEGORY_BANNER_CATEGORY_ID = 'GET_CATEGORY_BANNER_CATEGORY_ID';
export const CLEAR_CATEGORY_TYPE = 'CLEAR_CATEGORY_TYPE';
export const GET_CATEGORY_BANNER_TAG ='GET_CATEGORY_BANNER_TAG';
export const GET_CATEGORY_BANNER_TAG_ID = 'GET_CATEGORY_BANNER_TAG_ID';
export const GET_CATEGORY_BANNER_TYPE ='GET_CATEGORY_BANNER_TYPE';
export const GET_CATEGORY_BANNER_TYPE_ID = 'GET_CATEGORY_BANNER_TYPE_ID';
export const GET_CATEGORY_BANNER_DEFAULT = 'GET_CATEGORY_BANNER_DEFAULT';
export const GET_CATEGORY_BANNER_DEFAULT_ID = 'GET_CATEGORY_BANNER_DEFAULT_ID';
//PRODUCT
export const LOADING_PRODUCT ='LOADING_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const STOP_LOADING_PRODUCT ='STOP_LOADING_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const CREATE_DISCOUNT = 'CREATE_DISCOUNT';

//AUTH
export const AUTH_SET_ADMIN = 'AUTH_SET_ADMIN';
export const LOADING_AUTH_ADMIN = 'LOADING_AUTH_ADMIN';
export const AUTH_ADMIN_LOGOUT = 'AUTH_ADMIN_LOGOUT';
export const STOP_LOADING_AUTH = 'STOP_LOADING_AUTH';

// notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

//UI 
export const EDIT_SLIDER_HOME = 'EDIT_SLIDER_HOME';

//lookbook
export const GET_ALL_LOOKBOOK ='GET_ALL_LOOKBOOK';
export const LOADING_LOOKBOOK = 'LOADING_LOOKBOOK';
export const EDIT_LOOKBOOK ='EDIT_LOOKBOOK';
export const CLEAR_LOOKBOOK = 'CLEAR_LOOKBOOK';

// VOUCHER
export const GET_ALL_VOUCHER_TYPE ='GET_ALL_VOUCHER_TYPE';
export const GET_ALL_VOUCHER ='GET_ALL_VOUCHER';
export const LOADING_VOUCHER = 'LOADING_VOUCHER';
export const REMOVE_LOADING_VOUCHER ='REMOVE_LOADING_VOUCHER';
export const EDIT_VOUCHER = 'EDIT_VOUCHER';

// Sizing
export const LOADING_SIZING ='LOADING_SIZING';
export const REMOVE_LOADING_SIZING = 'REMOVE_LOADING_SIZING';
export const GET_ALL_SIZING = 'GET_ALL_SIZING';
export const EDIT_CURRENT_SIZE = 'EDIT_CURRENT_SIZE';
export const SET_SIZING = 'SET_SIZING';

//COLLECTION
export const GET_ALL_COLLECTION = 'GET_ALL_COLLECTION';
export const LOADING_COLLECTION = 'LOADING_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';
export const CLEAR_COLLECTION = 'CLEAR_COLLECTION';
export const SET_COLLECTION = 'SET_COLLECTION';

//ORDER
export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const LOADING_ORDER = 'LOADING_ORDER';
export const REMOVE_LOADING = 'REMOVE_LOADING';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const DOWNLOAD_DATA_ORDER = 'DOWNLOAD_DATA_ORDER';

// USER
export const USER={
    getAll:'USER:GET-ALL',
    loading:'USER:LOADING'
}

// cekresi
export const RESI={
    get:'RESI:CEKRESI',
    loading:'RESI:LOADING',
    
}

export const MEDIA={
    loading:"MEDIA:LOADING-UPLOAD",
    loading_percent:"MEDIA:LOADING-PERCENT",
    success:"MEDIA:SUCCESS",
    getMedia:"MEDIA:GET-MEDIA",
    delete:"MEDIA:DELETE",
    loadingProcess:"MEDIA:LOADING-PROCESS",
    removeLoading:"MEDIA:REMOVE-LOADING"
}

