export const product={
       activeStep: 2,
    skipped: new Set(),
    colors: [
      { original_color: 'red', hex_color: '#D50000', isActive: false },
      { original_color: 'pink', hex_color: '#C51162', isActive: false },
      { original_color: 'purple', hex_color: '#D500F9', isActive: false },
      { original_color: 'deepPurple', hex_color: '#311B92', isActive: false },
      { original_color: 'indigo', hex_color: '#3949AB', isActive: false },
      { original_color: 'blue', hex_color: '#2962FF', isActive: false },
      { original_color: 'lightBlue', hex_color: '#0091EA', isActive: false },
      { original_color: 'cyan', hex_color: '#00B8D4', isActive: false },
      { original_color: 'white', hex_color: '#FAFAFA', isActive: false },
      { original_color: 'teal', hex_color: '#004D40', isActive: false },
      { original_color: 'green', hex_color: '#00C853', isActive: false },
      { original_color: 'lightGreen', hex_color: '#64DD17', isActive: false },
      { original_color: 'lime', hex_color: '#AEEA00', isActive: false },
      { original_color: 'yellow', hex_color: '#FFD600', isActive: false },
      { original_color: 'amber', hex_color: '#FFAB00', isActive: false },
      { original_color: 'orange', hex_color: '#FF6D00', isActive: false },
      { original_color: 'deepOrange', hex_color: '#DD2C00', isActive: false },
      { original_color: 'brown', hex_color: '#3E2723', isActive: false },
      { original_color: 'grey', hex_color: '#9E9E9E', isActive: false },
      { original_color: 'blueGrey', hex_color: '#37474F', isActive: false },
      { original_color: 'black', hex_color: '#000000', isActive: false },

    ],
    product_variant: {
      hex_color: "#000000",
      original_color: "black",
    },
    product_attribute: [
      { size: 'M', stock: '22' },
      { size: 'L', stock: '5' },
    ],
    imageSelected: [
      {
      original: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL1.jpg",
      thumbnail: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL1.jpg",
      originalAlt: "hammerstout",
      thumbnailAlt: "hammerstout",
      originalTitle: "hammerstout",
      thumbnailTitle: "hammerstout",
      // description: asset.alt,
      public_id: "SWEATSHIRT/STENCIL1",
      size: 25267,
      height: 1080,
      width: 1080,
      tags:"stencil,keren"
    },
      {
        original: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL1.jpg",
        thumbnail: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL1.jpg",
        originalAlt: "hammerstout",
        thumbnailAlt: "hammerstout",
        originalTitle: "hammerstout",
        thumbnailTitle: "hammerstout",
        // description: asset.alt,
        public_id: "SWEATSHIRT/STENCIL1",
        size: 25267,
        height: 1080,
        width: 1080,
        tags: "stencil,keren"
      },
      {
        original: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL2.jpg",
        thumbnail: "https://res.cloudinary.com/hammerstout/image/upload/v2545650387/SWEATSHIRT/STENCIL2.jpg",
        originalAlt: "hammerstout",
        thumbnailAlt: "hammerstout",
        originalTitle: "hammerstout",
        thumbnailTitle: "hammerstout",
        // description: asset.alt,
        public_id: "SWEATSHIRT/STENCIL2",
        size: 25267,
        height: 1080,
        width: 1080,
        tags: "stencil,keren"
      },
      {
        original: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL3.jpg",
        thumbnail: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL3.jpg",
        originalAlt: "hammerstout",
        thumbnailAlt: "hammerstout",
        originalTitle: "hammerstout",
        thumbnailTitle: "hammerstout",
        // description: asset.alt,
        public_id: "SWEATSHIRT/STENCIL3",
        size: 25267,
        height: 1080,
        width: 1080,
        tags: "stencil,keren"
      },
      {
        original: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL4.jpg",
        thumbnail: "https://res.cloudinary.com/hammerstout/image/upload/v1545650387/SWEATSHIRT/STENCIL4.jpg",
        originalAlt: "hammerstout",
        thumbnailAlt: "hammerstout",
        originalTitle: "hammerstout",
        thumbnailTitle: "hammerstout",
        // description: asset.alt,
        public_id: "SWEATSHIRT/STENCIL4",
        size: 25267,
        height: 1080,
        width: 1080,
        tags: "stencil,keren"
      },

  ],
    product: {
      name: "STENCIL",
      slug: 'STENCIL',
      description: "<p>Type: Pullover Hoodie<br />Material: Cotton Fleece<br />Color: Black<br />READY SIZE<br />S , M , L , XL&nbsp;<br />Price: 305.000</p>",
      quantity: '',
      regular_price: "305.000",
    },
    isDiscountCard: true,
    product_discount: {
      discount_percentage: "10",
      discount_value: "274.500",
      valid_from: moment(new Date()).format('YYYY-MM-DD HH:mm:ss'),
      valid_until: moment(new Date()).format('YYYY-MM-DD HH:mm:ss'),
      date_created: moment(new Date()).format('YYYY-MM-DD HH:mm:ss'),
      coupon_code: ''
    }
}